# Generated by Django 5.1.1 on 2025-02-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_remove_pengguna_nama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pesan',
        ),
        migrations.DeleteModel(
            name='RoomChat',
        ),
    ]
