# Generated by Django 5.1.1 on 2025-02-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangLelang',
            fields=[
                ('lelang_dibuka', models.DateTimeField(auto_created=True)),
                ('kode', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(max_length=255)),
                ('harga_buka', models.IntegerField(default=0)),
                ('harga_saatini', models.IntegerField(default=0, editable=False)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_lelang/')),
                ('lelang_ditutup', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiLelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelelang', models.CharField(max_length=255)),
                ('harga_bid', models.IntegerField()),
                ('waktu_bid', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='lelang.baranglelang')),
            ],
        ),
    ]
