# Generated by Django 5.1.1 on 2025-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lelang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baranglelang',
            name='penjual',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
